// Exercises the real shared settings component with an isolated in-memory API.
// This fixture contains no replacement Harness chat interface.
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { resolve, extname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const fixture = `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/src/manager.css"><link rel="stylesheet" href="/src/scenes.css"><main id="toolbox"></main><script type="module">
import {mountManager} from '/src/manager.mjs';
import {defaults} from '/src/presets.mjs';
let state={...structuredClone(defaults),pet:{...defaults.pet,size:105},custom:{theme:[],splash:[],pet:[]}};let changed=()=>{};let serial=0;
window.readState=()=>structuredClone(state);window.poll=()=>changed(structuredClone(state));window.failNext=false;
window.updatePatches=[];window.holdSizeUpdates=false;window.pendingSizeWrites=[];
const api={desktop:true,get:async()=>structuredClone(state),onChange:fn=>(changed=fn,()=>{}),update:async patch=>{window.updatePatches.push(structuredClone(patch));if(window.holdSizeUpdates&&typeof patch.pet?.size==='number')await new Promise(resolve=>window.pendingSizeWrites.push(resolve));state={...state,...patch,pet:{...state.pet,...patch.pet}};changed(structuredClone(state));return structuredClone(state);},reset:async()=>state,
addPreset:async payload=>{if(window.failNext){window.failNext=false;throw Error('测试：保存失败，请重试');} const id='custom-'+(++serial);const preset={...payload,id,custom:true,asset:payload.image?.dataUrl,preview:payload.image?.dataUrl};state.custom[payload.kind].push(preset);return structuredClone(state);},
removePreset:async({kind,id})=>{state.custom[kind]=state.custom[kind].filter(p=>p.id!==id);if(kind==='pet'&&state.pet.id===id)state.pet.id=defaults.pet.id;else if(state[kind]===id)state[kind]=defaults[kind];return structuredClone(state);}};
window.unmount=mountManager(document.querySelector('#toolbox'),api,{assetResolver:p=>new Promise(resolve=>setTimeout(()=>resolve(p?.startsWith('data:')?p:'/'+p),20))});</script>`;
const server=createServer(async(req,res)=>{try{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end(fixture);return;}const path=resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!path.startsWith(root.endsWith(sep)?root:root+sep))throw Error('path');res.setHeader('Content-Type',({'.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[extname(path)]||'application/octet-stream');res.end(await readFile(path));}catch{res.statusCode=404;res.end('not found');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1100,height:920}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:${server.address().port}`);
 await page.getByRole('button',{name:'添加界面皮肤',exact:true}).click();
 const form=page.getByRole('dialog',{name:'添加界面皮肤'});
 await form.getByLabel('名称',{exact:true}).fill('我的清晨');
 await page.evaluate(()=>window.poll());
 assert.equal(await form.getByLabel('名称',{exact:true}).inputValue(),'我的清晨','polling preserves drafts');
 await form.getByLabel('强调色',{exact:true}).fill('#336688');
 await form.getByLabel('主背景',{exact:true}).fill('#f1ebff');
 await form.getByRole('button',{name:'保存到我的预设'}).click();
 assert.equal((await page.evaluate(()=>window.readState())).theme,'whalegirl','add must not apply');
 await page.locator('[data-preset="custom-1"]').waitFor();
 assert.equal((await page.evaluate(()=>window.readState())).custom.theme[0].palette.base,'#f1ebff','background color edits must be saved');
 // Repeated names are valid; stable unique IDs distinguish their cards.
 await page.getByRole('button',{name:'添加界面皮肤',exact:true}).click();
 await page.getByRole('dialog').getByLabel('名称',{exact:true}).fill('我的清晨');
 await page.getByRole('dialog').getByLabel('参考皮肤').selectOption('night');
 const nightPalette=(await import('../src/presets.mjs')).themes.find(t=>t.id==='night').palette;
 const actualPalette=await page.getByRole('dialog').locator('input[type=color]').evaluateAll(inputs=>Object.fromEntries(inputs.map(input=>[input.name,input.value])));
 assert.deepEqual(actualPalette,nightPalette,'reference selection must copy all ten colors');
 assert.equal(await page.getByRole('dialog').getByLabel('界面模式').inputValue(),'dark');
 await page.getByRole('dialog').getByRole('button',{name:'保存到我的预设'}).click();
 await page.locator('[data-preset="custom-2"]').waitFor();
 assert.deepEqual((await page.evaluate(()=>window.readState())).custom.theme[1].palette,nightPalette,'reference palette must be saved');
 assert.equal((await page.evaluate(()=>window.readState())).custom.theme.length,2);
 await page.locator('[data-preset="custom-1"] [data-apply]').click();
 await page.locator('[data-preset="custom-1"] [data-delete]').click();
 await page.evaluate(()=>window.poll());
 await page.locator('[data-preset="custom-1"]').getByRole('button',{name:'确认删除'}).click();
 await page.waitForFunction(()=>!document.querySelector('[data-preset="custom-1"]'));
 assert.equal((await page.evaluate(()=>window.readState())).theme,'whalegirl');
 await page.getByRole('button',{name:'添加界面皮肤',exact:true}).click();
 await page.getByRole('dialog').getByLabel('名称',{exact:true}).fill('保留我的草稿');
 await page.getByRole('dialog').getByLabel('导入主题 JSON').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":1,"kind":"theme","palette":{"base":"url(https://bad.invalid)"}}')});
 await page.getByRole('dialog').getByRole('alert').filter({hasText:'JSON'}).waitFor();
 assert.equal(await page.getByRole('dialog').getByLabel('名称',{exact:true}).inputValue(),'保留我的草稿');
 const exported=page.waitForEvent('download');
 await page.getByRole('dialog').getByRole('button',{name:'导出当前配色'}).click();
 const file=await exported;
 const themeData=JSON.parse(await readFile(await file.path(),'utf8'));
 assert.equal(themeData.version,1);assert.equal(themeData.kind,'theme');assert.equal(Object.keys(themeData.palette).length,10);
 await page.getByRole('dialog').getByLabel('导入主题 JSON').setInputFiles({name:'theme.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...themeData,name:'从 JSON 导入的皮肤',scheme:'dark'}))});
 await page.waitForFunction(()=>document.querySelector('[name=name]')?.value==='从 JSON 导入的皮肤');
 assert.equal(await page.getByRole('dialog').getByLabel('界面模式').inputValue(),'dark');
 await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
 await page.getByRole('button',{name:'添加界面皮肤',exact:true}).click();
 await page.evaluate(()=>{window.outerEscapeCount=0;document.addEventListener('keydown',event=>{if(event.key==='Escape')window.outerEscapeCount++;});});
 await page.getByRole('dialog').getByLabel('名称',{exact:true}).press('Escape');
 assert.equal(await page.getByRole('dialog').count(),0,'Escape closes the custom dialog');
 assert.equal(await page.evaluate(()=>window.outerEscapeCount),0,'Escape must not reach the outer native settings handler');
 assert.equal(await page.locator('#toolbox').count(),1);
 await page.getByRole('tab',{name:'桌面宠物'}).click();
 assert.equal(await page.locator('[data-preset="robot"]').count(),0,'retired robot is absent from the shared manager');
 await page.waitForFunction(()=>{const i=document.querySelector('[data-preset="cyberdad"] img');return i?.complete&&i.naturalWidth>0;});
 assert.equal(await page.locator('[data-preset="cyberdad"] .cb-sprite-preview img').evaluate(i=>i.naturalWidth===1774&&i.naturalHeight===887),true,'the new VI pet has a decoded atlas preview');
 await page.locator('[data-preset="cyberdad"]').hover();
 assert.equal(await page.locator('[data-preset="cyberdad"] .cb-sprite-preview img').evaluate(i=>getComputedStyle(i).transform),'none','hover must not rotate the atlas and reveal neighboring poses');
 await page.route('**/assets/cyberdad-atlas.png',route=>route.fulfill({status:404,body:'missing'}));
 await page.evaluate(()=>window.poll());
 await page.waitForFunction(()=>{const i=document.querySelector('[data-preset="cyberdad"] img');return i?.complete&&i.naturalWidth>0&&i.src.endsWith('/assets/whale.svg');});
 assert.equal(await page.locator('[data-preset="cyberdad"] img').evaluate(i=>i.getBoundingClientRect().width<=i.parentElement.getBoundingClientRect().width+1),true,'a missing atlas shows the full fallback icon');
 await page.unroute('**/assets/cyberdad-atlas.png');await page.evaluate(()=>window.poll());

 assert.equal(await page.getByAltText('赛博老爸品牌标识',{exact:true}).count(),1,'CyberDad brand logo remains independent from the pet catalog');
 const size=page.getByRole('slider',{name:'桌宠大小',exact:true});
 assert.equal(await size.getAttribute('min'),'80');assert.equal(await size.getAttribute('max'),'320');assert.equal(await size.getAttribute('step'),'1');
 assert.equal(await size.inputValue(),'105','existing integer sizes must match the slider thumb');
 assert.equal(await page.locator('.cb-size-heading output').textContent(),'105px');
 await page.getByRole('button',{name:'放大桌宠',exact:true}).click();await page.waitForFunction(()=>window.readState().pet.size===115);
 const sizeBox=await page.locator('.cb-pet-size').boundingBox(),petCardBox=await page.locator('.cb-card').first().boundingBox();
 assert.ok(sizeBox.y+sizeBox.height<=petCardBox.y,'size controls must precede pet cards');
 const initialPetId=(await page.evaluate(()=>window.readState())).pet.id;
 const sliderNode=await size.elementHandle();
 await size.press('Home');await page.waitForFunction(()=>window.readState().pet.size===80);
 assert.equal(await sliderNode.evaluate(el=>el.isConnected&&document.activeElement===el),true,'saving keeps the slider and keyboard focus');
 assert.equal(await page.getByRole('button',{name:'缩小桌宠',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'放大桌宠',exact:true}).click();await page.waitForFunction(()=>window.readState().pet.size===90);
 await page.getByRole('button',{name:'缩小桌宠',exact:true}).click();await page.waitForFunction(()=>window.readState().pet.size===80);
 assert.equal((await page.evaluate(()=>window.readState())).pet.id,initialPetId,'size buttons must not apply a different preset');
 await size.press('End');await page.waitForFunction(()=>window.readState().pet.size===320);
 assert.equal(await page.getByRole('button',{name:'放大桌宠',exact:true}).isDisabled(),true);
 await size.press('Home');await page.waitForFunction(()=>window.readState().pet.size===80);
 await page.evaluate(()=>{window.holdSizeUpdates=true;});
 await size.press('ArrowRight');await page.waitForFunction(()=>window.pendingSizeWrites.length===1);
 await page.evaluate(()=>window.poll());
 assert.equal(await size.inputValue(),'81','polling must not overwrite the active drag value');
 await size.press('ArrowRight');await page.evaluate(()=>window.poll());
 assert.equal(await size.inputValue(),'82');assert.equal(await sliderNode.evaluate(el=>el.isConnected&&document.activeElement===el),true,'continuous adjustment keeps the same focused control');
 await page.evaluate(()=>{window.holdSizeUpdates=false;window.pendingSizeWrites.splice(0).forEach(resolve=>resolve());});
 await page.waitForFunction(()=>window.readState().pet.size===82);
 assert.equal(await sliderNode.evaluate(el=>el.isConnected&&document.activeElement===el),true);
 assert.equal((await page.evaluate(()=>window.readState())).pet.id,initialPetId);
 await page.getByRole('button',{name:'添加桌面宠物',exact:true}).click();
 const petForm=page.getByRole('dialog');
 await petForm.getByLabel('名称',{exact:true}).fill('纸片鲸鱼');
 await petForm.getByLabel('选择图片').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('no')});
 await petForm.getByRole('alert').filter({hasText:'图片'}).waitFor();
 await petForm.getByLabel('选择图片').setInputFiles({name:'whale.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><circle cx="50" cy="50" r="40" fill="#88bbff"/></svg>')});
 await petForm.locator('.cb-upload-preview img').waitFor();
 await page.evaluate(()=>{window.failNext=true;window.poll();});
 await petForm.getByRole('button',{name:'保存到我的预设'}).click();
 await petForm.getByRole('alert').filter({hasText:'保存失败'}).waitFor();
 assert.equal(await petForm.getByLabel('名称',{exact:true}).inputValue(),'纸片鲸鱼');
 assert.equal(await petForm.locator('.cb-upload-preview img').count(),1,'failed save preserves uploaded preview');
 await petForm.getByRole('button',{name:'保存到我的预设'}).click();
 await page.locator('[data-preset="custom-3"]').waitFor();
 await page.getByRole('tab',{name:'启动画面'}).click();
 await page.getByRole('button',{name:'添加启动画面',exact:true}).click();
 const splashForm=page.getByRole('dialog');
 await splashForm.getByLabel('名称',{exact:true}).fill('自己的启动画面');
 await splashForm.getByLabel('背景颜色').fill('#ddeeff');
 await splashForm.getByLabel('动态风格').selectOption('stars');
 await splashForm.getByLabel('选择图片').setInputFiles({name:'morning.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><circle cx="50" cy="50" r="40" fill="#88bbff"/></svg>')});
 await splashForm.locator('.cb-upload-preview img').waitFor();
 await splashForm.getByRole('button',{name:'保存到我的预设'}).click();
 await page.locator('[data-preset="custom-4"]').waitFor();
 assert.equal((await page.evaluate(()=>window.readState())).splash,'whalegirl');
 await page.locator('[data-preset="custom-4"] [data-preview]').click();
 await page.waitForFunction(()=>{const img=document.querySelector('.cb-preview img');return img?.complete&&img.naturalWidth>0;});
 assert.equal(await page.locator('.cb-preview').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(221, 238, 255)');
 await page.getByRole('button',{name:'关闭预览'}).click();
 await page.locator('[data-preview="whale"]').click();
 await page.evaluate(()=>window.poll());
 await page.getByRole('button',{name:'关闭预览'}).waitFor();
 await page.getByRole('button',{name:'关闭预览'}).click();
 await page.route('**/whalegirl-startup.mp4',route=>route.fulfill({status:404,body:'missing'}));
 await page.locator('[data-preview="whalegirl"]').click();
 await page.getByRole('alert').filter({hasText:'视频加载失败'}).waitFor();
 assert.equal(await page.locator('.cb-video-preview video').getAttribute('src'),null,'failed video releases source');
 await page.getByRole('button',{name:'关闭预览'}).click();
 assert.equal(await page.locator('.cb-video-preview').count(),0);
 await page.getByRole('tab',{name:'桌面宠物'}).click();
 await page.route('**/assets/cat.svg',route=>route.fulfill({status:404,body:'missing'}));
 await page.evaluate(()=>window.poll());
 await page.waitForFunction(()=>{const img=document.querySelector('[data-preset="cat"] img');return img?.complete&&img.naturalWidth>0&&img.src.endsWith('/assets/whale.svg');});
 await page.route('**/assets/whale.svg',route=>route.fulfill({status:404,body:'missing'}));
 await page.evaluate(()=>window.poll());
 await page.waitForFunction(()=>{const img=document.querySelector('[data-preset="cat"] img');return img?.complete&&img.naturalWidth>0&&img.src.startsWith('data:image/svg+xml,');});
 const fallback=await page.locator('[data-preset="cat"] img').getAttribute('src');
 assert.match(decodeURIComponent(fallback),/data-creature="whale"/);
 assert.doesNotMatch(decodeURIComponent(fallback),/robot/,'even total asset failure must not resurrect the retired robot');
 await page.unroute('**/assets/cat.svg');await page.unroute('**/assets/whale.svg');
 await page.getByRole('tab',{name:'启动画面'}).click();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'添加启动画面',exact:true}).click();
 assert.ok(await page.getByRole('dialog').evaluate(el=>el.getBoundingClientRect().width<=window.innerWidth));
 await page.evaluate(()=>window.unmount());
 assert.equal(await page.getByRole('dialog').count(),0,'unmount closes owned overlays');
 assert.deepEqual(errors,[]);
 console.log('custom manager: size controls/focus/80px, add, palette edits, reference colors, JSON round-trip, Escape isolation, validation, polling drafts, retry, delete fallback, preview, retired robot removal and whale asset fallback PASS');
}finally{await browser.close();await new Promise(r=>server.close(r));}
