// Toolbox product copy is intentionally Chinese for the first release.
export const copy = {
  title: "赛博老爸的 Harness 换装器",
  headline: "给灵感，换个好心情。",
  subtitle: "一个工作界面，三种小小的改变。",
  saved: "已在本机保存",
  saving: "正在保存…",
  tabs: { splash: "启动画面", theme: "界面皮肤", pet: "桌面宠物" },
  apply: "应用",
  selected: "使用中",
  preview: "预览",
  reset: "恢复默认",
  disable: "关闭美化",
  enable: "开启美化",
  off: "美化已关闭",
  default: "Harness 原始外观",
  splashOff: "关闭启动动画",
  petOn: "显示桌宠",
  petOff: "隐藏桌宠",
  size: "桌宠大小",
  pause: "暂停动画",
  resume: "继续动画",
  foot: "三项独立组合 · 本地保存 · 离线素材",
  titles: {
    splash: "让每次出发，都值得期待。",
    theme: "让熟悉的工作，有一点新鲜。",
    pet: "认真工作，也有人陪。",
  },
  notes: {
    splash: "视频预设完整播放约 7 秒后进入 Harness，可点击跳过或按 Esc。",
    theme: "即时应用到真实 Harness，不打断会话与任务。",
    pet: "拖动调整位置，单击打招呼，右键打开菜单。",
  },
  browserPet: "桌宠需要本机伴随进程：运行 ./run.sh pet。",
  close: "关闭预览",
};
